# Development override: bind-mount source and enable autoreload
services:
  app:
    volumes:
      - ./backend:/app/backend:delegated
      - ./pyproject.toml:/app/pyproject.toml:ro
      - ./poetry.lock:/app/poetry.lock:ro
      # Optional: if you want local scripts
      - ./scripts:/app/scripts:delegated
      - ./artifacts/models:/app/artifacts/models
    environment:
      APP_ENV: local
      LOG_LEVEL: DEBUG
    command:
      - /app/.venv/bin/uvicorn
      - backend.apps.api.main:app
      - --host
      - 0.0.0.0
      - --port
      - "8000"
      - --reload
      - --reload-dir
      - backend

  frontend-dev:
    image: 'node:20'
    working_dir: /app
    command: ["sh","-c","sh ./scripts/dev-entry.sh"]
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    environment:
      VITE_BACKEND_URL: http://app:8000
      CHOKIDAR_USEPOLLING: 1
      WATCHPACK_POLLING: true
      FORCE_COLOR: 1
    ports:
      - "${FRONTEND_DEV_PORT:-5173}:5173"

volumes:
  frontend_node_modules:
