services:

  app:
    image: ghcr.io/${GH_OWNER:-${COMPOSE_PROJECT_NAME}}/pro11-backend:dev-latest
    container_name: pro11-app-dev
    env_file:
      - .env
      - .env.private
    environment:
      APP_ENV: local
      LOG_LEVEL: DEBUG
      # Backend DB connection (shared with local dev stack via host port)
      POSTGRES_HOST: host.docker.internal
      POSTGRES_PORT: "${DB_PORT:-55432}"
      POSTGRES_DB: mydata
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: traderpass
    ports:
      - "${APP_PORT:-8000}:8000"
    restart: unless-stopped

  frontend:
    image: ghcr.io/${GH_OWNER:-${COMPOSE_PROJECT_NAME}}/pro11-frontend:dev-latest
    container_name: pro11-frontend-dev
    environment:
      BACKEND_ORIGIN: http://app:8000
    depends_on:
      - app
    ports:
      - "${FRONTEND_PORT:-5173}:80"
    restart: unless-stopped
