# Explicit development compose file (hot reload + bind mounts)
services:

  db:
    image: postgres:15
    container_name: xrp-postgres-dev
    environment:
      POSTGRES_DB: mydata
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: traderpass
    volumes:
      - pgdata_dev:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d mydata"]
      interval: 5s
      timeout: 3s
      retries: 10
    ports:
      - "${DB_PORT:-55432}:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: xrp-app:dev
    env_file:
      - .env
      - .env.private
  # No DB dependency; app uses .env POSTGRES_* (host.docker.internal or external host)
    environment:
      APP_ENV: ${APP_ENV:-local}
      LOG_LEVEL: ${LOG_LEVEL:-DEBUG}
      # Align with local: disable fast startup so loops are not skipped
      FAST_STARTUP: ${FAST_STARTUP:-false}
      FAST_STARTUP_AUTO_UPGRADE: ${FAST_STARTUP_AUTO_UPGRADE:-true}
      DEV_RELOAD: ${DEV_RELOAD:-1}
      # Ensure core data pipelines and monitors are active by default for local dev
      INGESTION_ENABLED: ${INGESTION_ENABLED:-true}
      FEATURE_SCHED_INTERVAL: ${FEATURE_SCHED_INTERVAL:-60}
      INFERENCE_AUTO_LOOP_ENABLED: ${INFERENCE_AUTO_LOOP_ENABLED:-true}
      INFERENCE_AUTO_LOOP_INTERVAL: ${INFERENCE_AUTO_LOOP_INTERVAL:-15}
      AUTO_LABELER_ENABLED: ${AUTO_LABELER_ENABLED:-true}
      AUTO_LABELER_INTERVAL: ${AUTO_LABELER_INTERVAL:-30}
      AUTO_LABELER_MIN_AGE_SECONDS: ${AUTO_LABELER_MIN_AGE_SECONDS:-60}
      CALIBRATION_MONITOR_ENABLED: ${CALIBRATION_MONITOR_ENABLED:-true}
      CALIBRATION_MONITOR_INTERVAL: ${CALIBRATION_MONITOR_INTERVAL:-60}
      CALIBRATION_MONITOR_WINDOW_SECONDS: ${CALIBRATION_MONITOR_WINDOW_SECONDS:-3600}
      SYMBOL: ${SYMBOL:-XRPUSDT}
      INTERVAL: ${INTERVAL:-15m}
      # Align signal source & loops with local
      SIGNAL_SOURCE: ${SIGNAL_SOURCE:-ml}
      ML_AUTO_LOOP_ENABLED: ${ML_AUTO_LOOP_ENABLED:-true}
      ML_AUTO_EXECUTE_ENABLED: ${ML_AUTO_EXECUTE_ENABLED:-true}
      ML_AUTO_EXECUTE_PAPER: ${ML_AUTO_EXECUTE_PAPER:-true}
      LOW_BUY_EXIT_LOOP_ENABLED: ${LOW_BUY_EXIT_LOOP_ENABLED:-true}
      # Local bootstrap and relaxed promotion thresholds
      AUTO_BOOTSTRAP_LOCAL: ${AUTO_BOOTSTRAP_LOCAL:-1}
      BOOTSTRAP_BACKFILL_BARS: ${BOOTSTRAP_BACKFILL_BARS:-50000}
      PROMOTION_MIN_ABS_AUC_DELTA: ${PROMOTION_MIN_ABS_AUC_DELTA:-0.0005}
      PROMOTION_MAX_ECE_DEGRADATION: ${PROMOTION_MAX_ECE_DEGRADATION:-0.02}
      PROMOTION_MAX_BRIER_DEGRADATION: ${PROMOTION_MAX_BRIER_DEGRADATION:-0.02}
      PROMOTION_MIN_VAL_SAMPLES: ${PROMOTION_MIN_VAL_SAMPLES:-400}
      # Bottom label local caps
      BOTTOM_MIN_LABELS: ${BOTTOM_MIN_LABELS:-20}
      BOTTOM_OHLCV_FETCH_CAP: ${BOTTOM_OHLCV_FETCH_CAP:-80000}
      # --- Explicit DB settings (use local compose DB service) ---
      POSTGRES_HOST: db
      POSTGRES_PORT: "5432"
      POSTGRES_DB: mydata
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: traderpass
      SKIP_DB: "false"
      # DB 설정은 .env 값을 그대로 사용 (.env 에서 host.docker.internal 로 바꾸면 호스트 DB로 연결)
      # 로컬 컨테이너 Postgres 서비스(db)에 붙고 싶다면 .env 에 POSTGRES_HOST=db 로 지정하거나
      # 별도 프로필: `docker compose --env-file .env.dockerdb up -d` 형태 사용 권장
      # 중요: 기능 플래그는 env_file(.env)의 값을 그대로 사용하도록 여기서 오버라이드하지 않습니다.
      # Verified multi-feed list (BBC, HN, Coindesk, Verge, Ars)
      NEWS_RSS_FEEDS: ${NEWS_RSS_FEEDS:-https://feeds.bbci.co.uk/news/world/rss.xml,https://hnrss.org/frontpage,https://www.coindesk.com/arc/outboundfeeds/rss,https://www.theverge.com/rss/index.xml,https://feeds.arstechnica.com/arstechnica/index}
      # Force polling for watchfiles (Windows / some network FS issues)
      WATCHFILES_FORCE_POLLING: 1
    volumes:
      - ./backend:/app/backend
      - ./pyproject.toml:/app/pyproject.toml:ro
      - ./poetry.lock:/app/poetry.lock:ro
      - ./scripts:/app/scripts
      - ./artifacts/models:/app/artifacts/models
    # Windows bind mounts may not preserve +x; invoke via sh directly (no chmod needed)
    command: ["sh","-c","sh ./scripts/run-dev.sh"]
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "${APP_PORT:-8000}:8000"
    restart: unless-stopped

  frontend:
    image: 'node:20'
    working_dir: /app
    # Dev entry script ensures full deps (tailwindcss) present; uses marker file to skip repeated installs
    command: ["sh","-c","sh ./scripts/dev-entry.sh"]
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    ports:
      - "${FRONTEND_DEV_PORT:-5173}:5173"
    environment:
      # Frontend no longer sets a default NEWS_RSS_FEEDS; backend owns feed list.
      VITE_BACKEND_URL: http://app:8000
      CHOKIDAR_USEPOLLING: 1
      WATCHPACK_POLLING: true
      FORCE_COLOR: 1
    depends_on:
      - app

  prometheus:
    image: prom/prometheus:v2.53.0
    container_name: xrp-prometheus-dev
    command: ["--config.file=/etc/prometheus/prometheus.yml", "--web.enable-lifecycle"]
    volumes:
      - ./infra/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./infra/prometheus:/etc/prometheus/rules:ro
    ports:
      - "9090:9090"
    depends_on:
      - app

volumes:
  frontend_node_modules:
  pgdata_dev:
