# Dev-only override: bind-mount source and enable autoreload
# Use explicitly: docker compose -f docker-compose.yml -f docker-compose.dev.override.yml up -d
services:
  app:
    volumes:
      - ./backend:/app/backend:delegated
      - ./pyproject.toml:/app/pyproject.toml:ro
      - ./poetry.lock:/app/poetry.lock:ro
      - ./scripts:/app/scripts:delegated
      - ./artifacts/models:/app/artifacts/models
    environment:
      APP_ENV: local
      LOG_LEVEL: DEBUG
      FAST_STARTUP: "false"
      FAST_STARTUP_AUTO_UPGRADE: "true"
      SIGNAL_SOURCE: ml
      ML_AUTO_LOOP_ENABLED: "true"
      ML_AUTO_EXECUTE_ENABLED: "true"
      ML_AUTO_EXECUTE_PAPER: "true"
      LOW_BUY_EXIT_LOOP_ENABLED: "true"
      AUTO_BOOTSTRAP_LOCAL: "1"
      BOOTSTRAP_BACKFILL_BARS: "50000"
      PROMOTION_MIN_ABS_AUC_DELTA: "0.0005"
      PROMOTION_MAX_ECE_DEGRADATION: "0.02"
      PROMOTION_MAX_BRIER_DEGRADATION: "0.02"
      PROMOTION_MIN_VAL_SAMPLES: "400"
      BOTTOM_MIN_LABELS: "20"
      BOTTOM_OHLCV_FETCH_CAP: "80000"
    command:
      - /app/.venv/bin/uvicorn
      - backend.apps.api.main:app
      - --host
      - 0.0.0.0
      - --port
      - "8000"
      - --reload
      - --reload-dir
      - backend

  frontend-dev:
    image: 'node:20'
    working_dir: /app
    command: ["sh","-c","sh ./scripts/dev-entry.sh"]
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    environment:
      VITE_BACKEND_URL: http://app:8000
      CHOKIDAR_USEPOLLING: 1
      WATCHPACK_POLLING: true
      FORCE_COLOR: 1
    ports:
      - "${FRONTEND_DEV_PORT:-5173}:5173"

volumes:
  frontend_node_modules:
