services:
  app:
    image: ghcr.io/${GH_OWNER:-${COMPOSE_PROJECT_NAME}}/pro11-backend:latest
    container_name: pro11-app
    env_file:
      - .env
      - .env.private
    environment:
      APP_ENV: prod
      LOG_LEVEL: INFO
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    image: ghcr.io/${GH_OWNER:-${COMPOSE_PROJECT_NAME}}/pro11-frontend:latest
    container_name: pro11-frontend
    environment:
      BACKEND_ORIGIN: http://app:8000
    depends_on:
      - app
    ports:
      - "8080:80"
    restart: unless-stopped
