name: deploy-local

on:
  # SSH 기반 로컬 배포는 기본적으로 수동 + 명시적 토글일 때만 실행되도록 제한
  workflow_dispatch:
    inputs:
      enable_ssh_local:
        description: "Run SSH-based local deploy (not recommended; prefer runner-based deploy)"
        type: boolean
        required: true
        default: false

jobs:
  deploy-local-dev:
    # 수동 실행 + 입력 토글이 켜졌을 때만 실행
    if: ${{ github.event_name == 'workflow_dispatch' && inputs.enable_ssh_local == true }}
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    env:
      GH_OWNER: ${{ github.repository_owner }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ensure .env files from secrets (optional)
        run: |
          if [ -n "${{ secrets.DEV_ENV_B64 }}" ]; then
            echo "${{ secrets.DEV_ENV_B64 }}" | base64 -d > .env
          fi
          if [ -n "${{ secrets.DEV_ENV_PRIVATE_B64 }}" ]; then
            echo "${{ secrets.DEV_ENV_PRIVATE_B64 }}" | base64 -d > .env.private
          fi

      - name: Deploy to Local Server via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.LOCAL_DEPLOY_HOST }}
          username: ${{ secrets.LOCAL_DEPLOY_USER }}
          key: ${{ secrets.LOCAL_DEPLOY_SSH_KEY }}
          script: |
            export GHCR_USER="${{ github.actor }}"
            export GHCR_TOKEN="${{ secrets.GITHUB_TOKEN }}"
            export GH_OWNER="${{ github.repository_owner }}"
            export COMPOSE_PROJECT_NAME="${{ github.repository_owner }}"
            mkdir -p ~/pro11
            cd ~/pro11
            echo "$GHCR_TOKEN" | docker login ghcr.io -u "$GHCR_USER" --password-stdin
            docker compose -f docker-compose.dev.deploy.yml pull || true
            docker compose -f docker-compose.dev.deploy.yml up -d
            docker system prune -f
