name: deploy-dev-runner

on:
  workflow_run:
    workflows: ["docker-build"]
    types: [completed]
  workflow_dispatch:

permissions:
  contents: read
  packages: read

jobs:
  deploy:
    if: ${{ github.event_name == 'workflow_dispatch' || (github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'develop') }}
    # IMPORTANT: Ensure your remote self-hosted runner has label: 'dev' (Windows runner recommended).
    runs-on:
      - self-hosted
      - dev
    concurrency:
      group: deploy-dev-runner
      cancel-in-progress: false
    env:
      COMPOSE_FILE: docker-compose.dev.deploy.yml
      COMPOSE_PROJECT_NAME: ${{ github.repository_owner }}
    defaults:
      run:
        shell: powershell
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Deploy on Windows runner (Process policy bypass)
        shell: powershell
        run: |
          $ErrorActionPreference = 'Stop'
          Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass -Force
          Set-Location $env:GITHUB_WORKSPACE
          if ('${{ secrets.DEV_ENV_B64 }}' -ne '') {
            [System.Text.Encoding]::ASCII.GetString([System.Convert]::FromBase64String('${{ secrets.DEV_ENV_B64 }}')) | Out-File -FilePath .env -Encoding ascii -NoNewline
          }
          if ('${{ secrets.DEV_ENV_PRIVATE_B64 }}' -ne '') {
            [System.Text.Encoding]::ASCII.GetString([System.Convert]::FromBase64String('${{ secrets.DEV_ENV_PRIVATE_B64 }}')) | Out-File -FilePath .env.private -Encoding ascii -NoNewline
          }
          '${{ secrets.GITHUB_TOKEN }}' | docker login ghcr.io -u '${{ github.actor }}' --password-stdin
          docker compose -f $env:COMPOSE_FILE pull
          docker compose -f $env:COMPOSE_FILE up -d
          docker system prune -f
