name: deploy-local

on:
  workflow_run:
    workflows: ["docker-build"]
    types: [completed]
    branches: [develop]
  workflow_dispatch: {}

jobs:
  deploy-local-dev:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    runs-on: self-hosted
    defaults:
      run:
        shell: pwsh
    env:
      GH_OWNER: ${{ github.repository_owner }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ensure .env files from secrets (optional)
        shell: pwsh
        run: |
          $ErrorActionPreference = 'Stop'
          if ($env:DEV_ENV_B64) {
            [System.Convert]::FromBase64String($env:DEV_ENV_B64) | Set-Content -Encoding Byte .env
          }
          if ($env:DEV_ENV_PRIVATE_B64) {
            [System.Convert]::FromBase64String($env:DEV_ENV_PRIVATE_B64) | Set-Content -Encoding Byte .env.private
          }

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull images
        run: docker compose -f docker-compose.dev.deploy.yml pull
        continue-on-error: true

      - name: Up (detached)
        run: docker compose -f docker-compose.dev.deploy.yml up -d

      - name: Prune old images
        run: docker system prune -f
