name: deploy-dev

on:
  workflow_run:
    workflows: ["docker-build"]
    types: [completed]
    branches: [develop]
  workflow_dispatch: {}

jobs:
  deploy-dev:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test SSH Connection
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.DEV_DEPLOY_HOST }}
          username: ${{ secrets.DEV_DEPLOY_USER }}
          key: ${{ secrets.DEV_DEPLOY_SSH_KEY }}
          debug: true
          script: |
            echo "SSH connection successful!"
            whoami
            pwd
            ls -la ~
            docker --version

      - name: Upload compose file to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DEV_DEPLOY_HOST }}
          username: ${{ secrets.DEV_DEPLOY_USER }}
          key: ${{ secrets.DEV_DEPLOY_SSH_KEY }}
          debug: true
          source: docker-compose.dev.deploy.yml
          target: ~/pro11/

      - name: Deploy DEV over SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.DEV_DEPLOY_HOST }}
          username: ${{ secrets.DEV_DEPLOY_USER }}
          key: ${{ secrets.DEV_DEPLOY_SSH_KEY }}
          debug: true
          script_stop: true
          script: |
            export GHCR_USER="${{ github.actor }}"
            export GHCR_TOKEN="${{ secrets.GITHUB_TOKEN }}"
            export GH_OWNER="${{ github.repository_owner }}"
            export COMPOSE_PROJECT_NAME="${{ github.repository_owner }}"
            mkdir -p ~/pro11
            cd ~/pro11
            echo "$GHCR_TOKEN" | docker login ghcr.io -u "$GHCR_USER" --password-stdin
            docker compose -f docker-compose.dev.deploy.yml pull || true
            docker compose -f docker-compose.dev.deploy.yml up -d
            docker system prune -f
