name: deploy-dev-runner

on:
  workflow_run:
    workflows: ["docker-build"]
    types: [completed]
  workflow_dispatch:

permissions:
  contents: read
  packages: read

jobs:
  deploy:
    if: ${{ github.event_name == 'workflow_dispatch' || (github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'develop') }}
    # IMPORTANT: Ensure your remote self-hosted runner has label: 'dev' (Windows runner recommended).
    runs-on:
      - self-hosted
      - dev
    concurrency:
      group: deploy-dev-runner
      cancel-in-progress: false
    env:
      COMPOSE_FILE: docker-compose.dev.deploy.yml
      COMPOSE_PROJECT_NAME: ${{ github.repository_owner }}
    defaults:
      run:
        shell: cmd
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Deploy on Windows runner (cmd + PS Bypass inline)
        shell: cmd
        env:
          DEV_ENV_B64: ${{ secrets.DEV_ENV_B64 }}
          DEV_ENV_PRIVATE_B64: ${{ secrets.DEV_ENV_PRIVATE_B64 }}
          GHCR_USER: ${{ github.actor }}
          GHCR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd %GITHUB_WORKSPACE%
          if not "%DEV_ENV_B64%"=="" powershell -NoProfile -ExecutionPolicy Bypass -Command "[System.Text.Encoding]::ASCII.GetString([System.Convert]::FromBase64String($env:DEV_ENV_B64)) | Out-File -FilePath .env -Encoding ascii -NoNewline"
          if not "%DEV_ENV_PRIVATE_B64%"=="" powershell -NoProfile -ExecutionPolicy Bypass -Command "[System.Text.Encoding]::ASCII.GetString([System.Convert]::FromBase64String($env:DEV_ENV_PRIVATE_B64)) | Out-File -FilePath .env.private -Encoding ascii -NoNewline"
          echo %GHCR_TOKEN% | docker login ghcr.io -u %GHCR_USER% --password-stdin
          docker compose -f %COMPOSE_FILE% pull
          docker compose -f %COMPOSE_FILE% up -d
          docker system prune -f
