name: deploy-local

on:
  # Manual only with explicit toggle; do not run automatically from main
  workflow_dispatch:
    inputs:
      enable_local:
        description: 'Run local deploy (manual only)'
        type: boolean
        required: true
        default: false

jobs:
  deploy-local-dev:
    # Hard disabled to prevent any SSH/scp attempts from main as well
    if: ${{ false }}
    runs-on: self-hosted
    env:
      GH_OWNER: ${{ github.repository_owner }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ensure .env files from secrets (optional)
        shell: bash
        run: |
          set -euo pipefail
          if [[ -n "${{ secrets.DEV_ENV_B64 }}" ]]; then echo "${{ secrets.DEV_ENV_B64 }}" | base64 -d > .env; fi
          if [[ -n "${{ secrets.DEV_ENV_PRIVATE_B64 }}" ]]; then echo "${{ secrets.DEV_ENV_PRIVATE_B64 }}" | base64 -d > .env.private; fi

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull images
        run: docker compose -f docker-compose.dev.deploy.yml pull
        continue-on-error: true

      - name: Up (detached)
        run: docker compose -f docker-compose.dev.deploy.yml up -d

      - name: Prune old images
        run: docker system prune -f
